const nameList = [
    'Time', 'Past', 'Future', 'Dev',
    'Fly', 'Flying', 'Soar', 'Soaring', 'Power', 'Falling',
    'Fall', 'Jump', 'Cliff', 'Mountain', 'Rend', 'Red', 'Blue',
    'Green', 'Yellow', 'Gold', 'Demon', 'Demonic', 'Panda', 'Cat',
    'Kitty', 'Kitten', 'Zero', 'Memory', 'Trooper', 'XX', 'Bandit',
    'Fear', 'Light', 'Glow', 'Tread', 'Deep', 'Deeper', 'Deepest',
    'Mine', 'Your', 'Worst', 'Enemy', 'Hostile', 'Force', 'Video',
    'Game', 'Donkey', 'Mule', 'Colt', 'Cult', 'Cultist', 'Magnum',
    'Gun', 'Assault', 'Recon', 'Trap', 'Trapper', 'Redeem', 'Code',
    'Script', 'Writer', 'Near', 'Close', 'Open', 'Cube', 'Circle',
    'Geo', 'Genome', 'Germ', 'Spaz', 'Shot', 'Echo', 'Beta', 'Alpha',
    'Gamma', 'Omega', 'Seal', 'Squid', 'Money', 'Cash', 'Lord', 'King',
    'Duke', 'Rest', 'Fire', 'Flame', 'Morrow', 'Break', 'Breaker', 'Numb',
    'Ice', 'Cold', 'Rotten', 'Sick', 'Sickly', 'Janitor', 'Camel', 'Rooster',
    'Sand', 'Desert', 'Dessert', 'Hurdle', 'Racer', 'Eraser', 'Erase', 'Big',
    'Small', 'Short', 'Tall', 'Sith', 'Bounty', 'Hunter', 'Cracked', 'Broken',
    'Sad', 'Happy', 'Joy', 'Joyful', 'Crimson', 'Destiny', 'Deceit', 'Lies',
    'Lie', 'Honest', 'Destined', 'Bloxxer', 'Hawk', 'Eagle', 'Hawker', 'Walker',
    'Zombie', 'Sarge', 'Capt', 'Captain', 'Punch', 'One', 'Two', 'Uno', 'Slice',
    'Slash', 'Melt', 'Melted', 'Melting', 'Fell', 'Wolf', 'Hound',
    'Legacy', 'Sharp', 'Dead', 'Mew', 'Chuckle', 'Bubba', 'Bubble', 'Sandwich', 'Smasher', 'Extreme', 'Multi', 'Universe', 'Ultimate', 'Death', 'Ready', 'Monkey', 'Elevator', 'Wrench', 'Grease', 'Head', 'Theme', 'Grand', 'Cool', 'Kid', 'Boy', 'Girl', 'Vortex', 'Paradox'
];

export function generateRandomName() {
    return nameList[Math.floor(Math.random() * nameList.length)];
};

const frontendChat = [
    "Loving Tailwind! 🚀",
    "Just fixed a flexbox bug! 😅",
    "CSS Grid is 🔥",
    "Finally nailed dark mode 🌙",
    "TypeScript is life-changing! 😍",
    "Struggling with z-index again 😵",
    "Flexbox for the win 💪",
    "Hooks > Class components 😏",
    "Added lazy loading today ⚡",
    "PostCSS is super useful 🌈",
    "Learning Framer Motion ✨",
    "Responsive design done! 📱",
    "Webpack config is tricky 🤔",
    "CSS animations look smooth 💫",
    "Inline styles = highest specificity!",
    "Axios is super clean 👍",
    "Love destructuring in ES6 💥",
    "Finally using useReducer properly 😄",
    "Media queries are a lifesaver 🎯",
    "Just started using Vue.js 🙈",
    "Styled-components = magic 🎨",
    "Console is finally error-free 🎉",
    "Testing on real devices 👀",
    "Utility-first CSS is amazing 🎉",
    "Implemented infinite scroll today 🔄",
    "Switched to hooks, no regrets 😅",
    "CSS variables are a game changer!",
    "Learning accessibility 🛠️",
    "Refactoring with TypeScript 🛠️",
    "Lighthouse audit score went up! 🚀",
    "Finally got rid of that bug 😅",
    "Lazy loading is so cool ⚡",
    "Custom hook cleaned up my code 🧼",
    "Testing on actual devices now 📱",
    "Infinite scroll is working! 🔄",
    "Finally got CSS transitions right 💫",
    "Switching to mobile-first 📱",
    "Webpack is still confusing 😵",
    "Grid layout looks awesome! 💪",
    "Working on a new layout 🧩",
    "Finally understand CSS Grid 🎉",
    "Just deployed my site! 🚀",
    "Flexbox makes centering easy 😅",
    "React DevTools are a lifesaver 🛠️",
    "useContext is super handy 👌",
    "Just added a loading spinner 🌀",
    "Starting with Framer Motion ✨",
    "Struggling with Webpack config 😅",
    "React.memo saved me! 💥",
    "Can’t wait for the weekend! 🎉",
    "Had a coffee break, feeling refreshed ☕",
    "Caught up on some coding podcasts 🎧",
    "Weekend plans? Coding and relaxing 😎",
    "Just saw a cool web design trend 🖌️",
    "Need to catch up on React docs 📚",
    "Anyone tried the new CSS framework? 🤔",
    "Feeling productive today, got a lot done! 👍",
    "Code reviews are going smoothly 😄",
    "Looking forward to trying out new tools! 🛠️",
    "Great chat with the team today! 🙌",
    "Just finished a big feature, time to celebrate! 🎉",
    "CSS variables are a game changer!",
    "Learning accessibility 🛠️",
    "Refactoring with TypeScript 🛠️",
    "Lighthouse audit score went up! 🚀",
    "Finally got rid of that bug 😅",
    "Lazy loading is so cool ⚡",
    "Custom hook cleaned up my code 🧼",
    "Testing on actual devices now 📱",
    "Infinite scroll is working! 🔄",
    "Finally got CSS transitions right 💫",
    "Switching to mobile-first 📱",
    "Webpack is still confusing 😵",
    "Grid layout looks awesome! 💪",
    "Working on a new layout 🧩",
    "Finally understand CSS Grid 🎉",
    "Just deployed my site! 🚀",
    "Flexbox makes centering easy 😅",
    "React DevTools are a lifesaver 🛠️",
    "useContext is super handy 👌",
    "Just added a loading spinner 🌀",
    "Starting with Framer Motion ✨",
    "Struggling with Webpack config 😅",
    "React.memo saved me! 💥"
];

export function generateRandomChat() {
    return frontendChat[Math.floor(Math.random() * frontendChat.length)];
};